name: Web-Test-Runner Guidepup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  web-test-runner_guidepup:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Enable VoiceOver Automation
        uses: guidepup/setup-action@0.1.3
      - name: Install Dependencies
        run: npm ci
      - name: VoiceOver Test
        run: npm run web-test-runner_guidepup_fails
